<a href="https://colab.research.google.com/github/EmmanuelBanguraa/EmmanuelBanguraa/blob/main/Project1_FOCI_Dashboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
supplier_name="Acme Defense Corp"

In [4]:
print(supplier_name)

Acme Defense Corp

In [5]:
suppliers=["Acme Defense Corp", "Global Parts Inc","Northstar Components"]
print (suppliers)

['Acme Defense Corp', 'Global Parts Inc', 'Northstar Components']

In [6]:
print (suppliers[0])
print (suppliers[-1])

Acme Defense Corp
Northstar Components

In [7]:
suppliers.append("Test Supplier")
print(suppliers)

['Acme Defense Corp', 'Global Parts Inc', 'Northstar Components', 'Test Supplier']

In [8]:
supplier = {
    "name" : "Acme Defense Corp" ,
    "country" : "USA",
    "risk score" : 7.5,
    "is_foreign_owned" : False
}
print(supplier["name"])
print(supplier["risk score"])

Acme Defense Corp
7.5

In [9]:
supplier2 = {
    "name" : "Shenzhen Components Ltd",
    "country": "China",
    "risk_score": 8.9,
    "is_foreign_owned" : True
}

print(supplier2["name"])
print(supplier2["risk_score"])

Shenzhen Components Ltd
8.9

In [10]:
supplier_list = [{"name": "Acme Defense Corp", "risk_score": 7.5}, {"name": "Global Parts Inc", "risk_score": 3.2}]

In [11]:
for s in supplier_list :
    print (s["name"], "-", s["risk_score"])

Acme Defense Corp - 7.5
Global Parts Inc - 3.2

In [12]:
for s in supplier_list :
  if s["risk_score"] >=7:
    print(s["name"], "is HIGH RISK")
  elif s ["risk_score"] >= 4:
    print(s["name"], "is MEDIUM RISK")
  else:
    print(s["name"], "is LOW RISK")

Acme Defense Corp is HIGH RISK
Global Parts Inc is LOW RISK

In [13]:
import pandas as pd
import random

In [14]:
company_names = ["Acme Defense", "Global Parts", "Northstar Compents", "Sentinel Systems","Vanguard Industries", "Titan Manufacturing","Apex Electronics", "Ironclad Supply","Falcon Aerospace","Summit Machining"]
countries = ["USA","China","Germany","Taiwan","South Korea","Japan","Mexico","India"]
industries =["Electronics","Machined Parts","Software","Raw Materials","Circuit Boards","Optics"]

In [15]:
suppliers = []
for i in range(40) :
    supplier = {
        "supplier_id" : i + 1,
        "name" : random.choice(company_names) + " " + str(i+ 1),
        "country" : random.choice(countries),
        "industry" : random.choice(industries),
        "risk_score" : round(random.uniform(1,10),1),
        "is_foreign_owned" : random.choice([True,False]),
        "single_source" : random.choice([True, False])
    }
    suppliers.append(supplier)

print(suppliers[0])
print(suppliers[1])

{'supplier_id': 1, 'name': 'Falcon Aerospace 1', 'country': 'Japan', 'industry': 'Circuit Boards', 'risk_score': 6.6, 'is_foreign_owned': False, 'single_source': False}
{'supplier_id': 2, 'name': 'Ironclad Supply 2', 'country': 'India', 'industry': 'Electronics', 'risk_score': 2.9, 'is_foreign_owned': True, 'single_source': False}

In [16]:
df = pd.DataFrame(suppliers)
df.head()

,supplier_id,name,country,industry,risk_score,is_foreign_owned,single_source
0,1,Falcon Aerospace 1,Japan,Circuit Boards,6.6,False,False
1,2,Ironclad Supply 2,India,Electronics,2.9,True,False
2,3,Acme Defense 3,South Korea,Circuit Boards,7.5,False,True
3,4,Titan Manufacturing 4,Mexico,Electronics,3.5,False,False
4,5,Northstar Compents 5,China,Circuit Boards,7.7,False,True

In [17]:
df . to_csv("suppliers.csv", index=False)

In [18]:
df2 = pd.read_csv("suppliers.csv")
df2.head()

,supplier_id,name,country,industry,risk_score,is_foreign_owned,single_source
0,1,Falcon Aerospace 1,Japan,Circuit Boards,6.6,False,False
1,2,Ironclad Supply 2,India,Electronics,2.9,True,False
2,3,Acme Defense 3,South Korea,Circuit Boards,7.5,False,True
3,4,Titan Manufacturing 4,Mexico,Electronics,3.5,False,False
4,5,Northstar Compents 5,China,Circuit Boards,7.7,False,True

In [19]:
import pandas as pd

df = pd.read_csv("suppliers.csv")
df.head()

,supplier_id,name,country,industry,risk_score,is_foreign_owned,single_source
0,1,Falcon Aerospace 1,Japan,Circuit Boards,6.6,False,False
1,2,Ironclad Supply 2,India,Electronics,2.9,True,False
2,3,Acme Defense 3,South Korea,Circuit Boards,7.5,False,True
3,4,Titan Manufacturing 4,Mexico,Electronics,3.5,False,False
4,5,Northstar Compents 5,China,Circuit Boards,7.7,False,True

In [20]:
def calculate_foci_risk(row):
    score = row["risk_score"]

    if row["is_foreign_owned"]:
        score += 2

    if row["single_source"]:
        score +=1

    if score >=8:
        return "HIGH RISK"
    elif score >=5:
        return "MEDIUM RISK"
    else:
        return "LOW RISK"

In [21]:
df["foci_risk"] = df.apply(calculate_foci_risk, axis=1)
df.head(10)

,supplier_id,name,country,industry,risk_score,is_foreign_owned,single_source,foci_risk
0,1,Falcon Aerospace 1,Japan,Circuit Boards,6.6,False,False,MEDIUM RISK
1,2,Ironclad Supply 2,India,Electronics,2.9,True,False,LOW RISK
2,3,Acme Defense 3,South Korea,Circuit Boards,7.5,False,True,HIGH RISK
3,4,Titan Manufacturing 4,Mexico,Electronics,3.5,False,False,LOW RISK
4,5,Northstar Compents 5,China,Circuit Boards,7.7,False,True,HIGH RISK
5,6,Vanguard Industries 6,Japan,Circuit Boards,7.3,True,True,HIGH RISK
6,7,Sentinel Systems 7,China,Software,2.7,False,True,LOW RISK
7,8,Titan Manufacturing 8,USA,Software,3.8,True,True,MEDIUM RISK
8,9,Acme Defense 9,Mexico,Circuit Boards,7.5,False,True,HIGH RISK
9,10,Ironclad Supply 10,Mexico,Software,1.3,False,True,LOW RISK

In [22]:
df["foci_risk"]. value_counts()

foci_risk
HIGH RISK      22
LOW RISK       10
MEDIUM RISK     8
Name: count, dtype: int64

In [23]:
df.to_csv("suppliers_scored.csv", index=False)